import type { Locale } from "@/lib/i18n";

const en =
  "Hey. No rush, no judgment. Just tell me what's on your mind — anything.";

export const CHAT_INTROS: Record<Locale, string> = {
  en,
  hr: "Hej. Bez žurbe, bez osuđivanja. Samo mi reci što ti je na umu — bilo što.",
  de: "Hey. Kein Stress, kein Urteil. Sag mir einfach, was dir durch den Kopf geht — irgendetwas.",
  es: "Hola. Sin prisa, sin juicios. Cuéntame qué tienes en mente — lo que sea.",
  fr: "Salut. Pas de précipitation, pas de jugement. Dis-moi simplement ce qui te passe par la tête — n'importe quoi.",
  it: "Ciao. Nessuna fretta, nessun giudizio. Dimmi solo cosa hai in mente — qualsiasi cosa.",
  pt: "Olá. Sem pressa, sem julgamentos. Diz-me só o que tens em mente — seja o que for.",
  ru: "Привет. Без спешки, без осуждения. Просто расскажи, что у тебя на уме — что угодно.",
  pl: "Hej. Bez pośpiechu, bez osądu. Po prostu powiedz, co masz w głowie — cokolwiek.",
  nl: "Hoi. Geen haast, geen oordeel. Vertel me gewoon wat er in je omgaat — alles mag.",
  tr: "Selam. Acele yok, yargı yok. Aklından geçenleri anlat — her şey olur.",
  ar: "مرحباً. بلا استعجال، بلا حكم. فقط أخبرني بما يدور في ذهنك — أي شيء.",
  zh: "你好。不用着急，不必评判。只管告诉我你在想什么——什么都可以。",
  "zh-TW": "你好。不用著急，不必評判。只管告訴我你在想什麼——什麼都可以。",
  ja: "こんにちは。急がなくていいし、判断もしない。今思っていることを何でも話してみて。",
  ko: "안녕하세요. 서두르지 않아도 되고, 판단하지 않을게요. 지금 마음에 있는 것을 아무거나 말해 주세요.",
  sv: "Hej. Ingen brådska, inget dömande. Berätta bara vad du har på hjärtat — vad som helst.",
  no: "Hei. Ingen hast, ingen dømming. Bare fortell meg hva som er på sinnet ditt — hva som helst.",
  da: "Hej. Ingen hast, ingen dømmekraft. Fortæl mig bare, hvad der er på dit sind — hvad som helst.",
  fi: "Hei. Ei kiirettä, ei tuomitsemista. Kerro vain, mitä mielessäsi on — mitä vain.",
  cs: "Ahoj. Bez spěchu, bez souzení. Řekni mi prostě, co máš na mysli — cokoli.",
  sk: "Ahoj. Bez ponáhľania, bez súdenia. Povedz mi len, čo máš na mysli — čokoľvek.",
  hu: "Szia. Nincs sietség, nincs ítélet. Csak mondd el, mi jár a fejedben — bármi.",
  ro: "Bună. Fără grabă, fără judecată. Spune-mi doar ce ai în minte — orice.",
  bg: "Здравей. Без бързане, без осъждане. Просто ми кажи какво ти е на ум — каквото и да е.",
  sr: "Hej. Bez žurbe, bez osude. Samo mi reci šta ti je na umu — bilo šta.",
  bs: "Hej. Bez žurbe, bez osuđivanja. Samo mi reci šta ti je na umu — bilo šta.",
  sl: "Hej. Brez hitenja, brez obsojanja. Samo povej, kaj imaš v mislih — karkoli.",
  uk: "Привіт. Без поспіху, без осуду. Просто скажи, що у тебе на думці — що завгодно.",
  el: "Γεια σου. Χωρίς βιασύνη, χωρίς κρίση. Πες μου απλά τι σου περνάει από το μυαλό — οτιδήποτε.",
  he: "היי. בלי לחץ, בלי שיפוט. פשוט ספר לי מה עובר לך בראש — כל דבר.",
  hi: "नमस्ते। कोई जल्दी नहीं, कोई निर्णय नहीं। बस बताओ, मन में क्या है — कुछ भी।",
  bn: "হ্যালো। কোনো তাড়াহুড়ো নেই, কোনো বিচার নেই। শুধু বলুন, মনে কী আছে — যেকোনো কিছু।",
  ur: "سلام۔ کوئی جلدی نہیں، کوئی فیصلہ نہیں۔ بس بتائیں، ذہن میں کیا ہے — کچھ بھی۔",
  fa: "سلام. عجله‌ای نیست، قضاوتی نیست. فقط بگو چه چیزی ذهنت را مشغول کرده — هر چیزی.",
  th: "สวัสดี ไม่ต้องรีบ ไม่ต้องตัดสิน แค่บอกว่าคุณกำลังคิดอะไรอยู่ — อะไรก็ได้",
  vi: "Xin chào. Không vội, không phán xét. Cứ nói cho tôi biết bạn đang nghĩ gì — bất cứ điều gì.",
  id: "Hai. Tidak perlu terburu-buru, tanpa penghakiman. Ceritakan saja apa yang ada di pikiranmu — apa saja.",
  ms: "Hai. Jangan tergesa-gesa, tanpa penghakiman. Beritahu sahaja apa yang ada di fikiran anda — apa-apa sahaja.",
  tl: "Kumusta. Walang apurahan, walang hatol. Sabihin mo lang kung ano ang nasa isip mo — kahit ano.",
  sw: "Habari. Hakuna haraka, hakuna hukumu. Niambie tu unachofikiria — chochote.",
  af: "Haai. Geen haas nie, geen oordeel nie. Vertel my net wat op jou gedagtes is — enigiets.",
  et: "Hei. Pole kiirust, pole hukkamist. Ütle lihtsalt, mis sul mõttes on — mis tahes.",
  lt: "Labas. Jokio skubėjimo, jokio vertinimo. Tiesiog pasakyk, kas galvoje — bet ką.",
  lv: "Sveiki. Nav steigas, nav sprieduma. Vienāk pasaki, kas tev ir prātā — jebko.",
  mk: "Здраво. Без брзање, без осуда. Само кажи што ти е на ум — било што.",
  sq: "Përshëndetje. Pa nxitim, pa gjykim. Thuaj thjesht çfarë ke në mendje — çfarëdo gjëje.",
  mn: "Сайн уу. Яаралгүй, шүүлгүй. Зүгээр л юу бодож байгаагаа хэлээрэй — юу ч болно.",
  ne: "नमस्ते। कुनै हतार छैन, कुनै निर्णय छैन। मनमा के छ भनेर भन्नुहोस् — जे पनि।",
  pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ। ਕੋਈ ਜਲਦਬਾਜ਼ੀ ਨਹੀਂ, ਕੋਈ ਫੈਸਲਾ ਨਹੀਂ। ਬੱਸ ਦੱਸੋ, ਦਿਮਾਗ ਵਿੱਚ ਕੀ ਹੈ — ਕੁਝ ਵੀ।",
  gu: "નમસ્તે. કોઈ ઉતાવળ નહીં, કોઈ નિર્ણય નહીં. ફક્ત કહો, મનમાં શું છે — કંઈ પણ.",
  ta: "வணக்கம். அவசரம் இல்லை, தீர்ப்பு இல்லை. உங்கள் மனதில் என்ன இருக்கிறது என்று சொல்லுங்கள் — எதுவும்.",
  te: "హాయ్. తొందర లేదు, నిర్ణయం లేదు. మీ మనస్సులో ఏముందో చెప్పండి — ఏదైనా.",
  kn: "ನಮಸ್ಕಾರ. ಯಾವುದೇ ಆತುರವಿಲ್ಲ, ಯಾವುದೇ ನಿರ್ಣಯವಿಲ್ಲ. ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿರುವುದನ್ನು ಹೇಳಿ — ಏನಾದರೂ.",
  ha: "Sannu. Babu gaggawa, babu hukunci. Ka gaya mini abin da ke tunaninka — komai ne.",
  yo: "Pẹ̀lẹ́. Kò sí iyara, kò sí ìdájọ. Sọ fún mi ohun tí ó wà lọ́kàn rẹ — ohunkóhun.",
  am: "ሰላም። ግዜ የለም፣ ፍርድ የለም። በማሰብዎ ላይ ያለውን ብቻ ንገሩኝ — ማንኛውም ነገር።",
};
