import type { Locale } from "@/lib/i18n";

const en = "Nobody else sees what you write.";

export const PRIVACY_LINES: Record<Locale, string> = {
  en,
  hr: "Nitko drugi ne vidi što pišete.",
  de: "Niemand sonst sieht, was du schreibst.",
  es: "Nadie más ve lo que escribes.",
  fr: "Personne d'autre ne voit ce que vous écrivez.",
  it: "Nessun altro vede quello che scrivi.",
  pt: "Mais ninguém vê o que escreves.",
  ru: "Больше никто не видит то, что вы пишете.",
  pl: "Nikt inny nie widzi tego, co piszesz.",
  nl: "Niemand anders ziet wat je schrijft.",
  tr: "Yazdıklarını başka kimse göremez.",
  ar: "لا أحد غيرك يرى ما تكتبه.",
  zh: "没有其他人能看到你写的内容。",
  "zh-TW": "沒有其他人能看到你寫的內容。",
  ja: "あなたが書いたことは、他の誰にも見えません。",
  ko: "당신이 쓴 내용은 다른 누구도 볼 수 없어요.",
  sv: "Ingen annan ser det du skriver.",
  no: "Ingen andre ser det du skriver.",
  da: "Ingen andre ser det, du skriver.",
  fi: "Kukaan muu ei näe mitä kirjoitat.",
  cs: "Nikdo jiný nevidí, co píšete.",
  sk: "Nikto iný nevidí, čo píšete.",
  hu: "Senki más nem látja, amit írsz.",
  ro: "Nimeni altcineva nu vede ce scrii.",
  bg: "Никой друг не вижда какво пишете.",
  sr: "Niko drugi ne vidi šta pišete.",
  bs: "Niko drugi ne vidi šta pišete.",
  sl: "Nihče drug ne vidi, kar pišete.",
  uk: "Більше ніхто не бачить те, що ви пишете.",
  el: "Κανείς άλλος δεν βλέπει αυτό που γράφεις.",
  he: "אף אחד אחר לא רואה את מה שאתה כותב.",
  hi: "आप जो लिखते हैं, वह कोई और नहीं देखता।",
  bn: "আপনি যা লেখেন, তা আর কেউ দেখতে পায় না।",
  ur: "آپ جو لکھتے ہیں، کوئی اور نہیں دیکھتا۔",
  fa: "هیچ‌کس جز شما نمی‌بیند چه می‌نویسید.",
  th: "ไม่มีใครเห็นสิ่งที่คุณเขียนนอกจากคุณ",
  vi: "Không ai khác thấy những gì bạn viết.",
  id: "Tidak ada orang lain yang melihat apa yang Anda tulis.",
  ms: "Tiada orang lain melihat apa yang anda tulis.",
  tl: "Walang iba ang makakakita ng isinusulat mo.",
  sw: "Hakuna mtu mwingine anayeona unachoandika.",
  af: "Niemand anders sien wat jy skryf nie.",
  et: "Keegi teine ei näe seda, mida sa kirjutad.",
  lt: "Niekas kitas nemato to, ką rašote.",
  lv: "Neviens cits neredz to, ko rakstāt.",
  mk: "Никој друг не го гледа она што го пишете.",
  sq: "Askush tjetër nuk sheh atë që shkruan.",
  mn: "Таны бичснийг өөр хэн ч харахгүй.",
  ne: "तपाईंले लेख्नुभएको कुरा अरू कसैले देख्दैन।",
  pa: "ਤੁਹਾਡੇ ਲਿਖੇ ਨੂੰ ਹੋਰ ਕੋਈ ਨਹੀਂ ਦੇਖਦਾ।",
  gu: "તમે શું લખો છો તે બીજું કોઈ જોઈ શકતું નથી.",
  ta: "நீங்கள் எழுதுவதை வேறு யாரும் பார்க்க மாட்டார்கள்.",
  te: "మీరు రాసింది మరెవరూ చూడరు.",
  kn: "ನೀವು ಬರೆಯುವುದನ್ನು ಬೇರೆ ಯಾರೂ ನೋಡುವುದಿಲ್ಲ.",
  ha: "Babu wanda zai ga abin da ka rubuta.",
  yo: "Ko si ẹlòmíràn tí yó rí ohun tí o kọ.",
  am: "የሚጽፉት ሌላ ማንም አይያይም።",
};
