import type { Locale } from "@/lib/i18n";

const en = "No wrong answers. No judgment. One question at a time.";

export const TRUST_LINES: Record<Locale, string> = {
  en,
  hr: "Nema krivih odgovora. Nema osuđivanja. Jedno pitanje odjednom.",
  de: "Keine falschen Antworten. Kein Urteil. Eine Frage nach der anderen.",
  es: "No hay respuestas incorrectas. Sin juicios. Una pregunta cada vez.",
  fr: "Pas de mauvaises réponses. Pas de jugement. Une question à la fois.",
  it: "Nessuna risposta sbagliata. Nessun giudizio. Una domanda alla volta.",
  pt: "Não há respostas erradas. Sem julgamentos. Uma pergunta de cada vez.",
  ru: "Нет неправильных ответов. Без осуждения. Одно за раз.",
  pl: "Nie ma złych odpowiedzi. Bez osądu. Jedno pytanie na raz.",
  nl: "Geen foute antwoorden. Geen oordeel. Eén vraag tegelijk.",
  tr: "Yanlış cevap yok. Yargı yok. Her seferinde bir soru.",
  ar: "لا إجابات خاطئة. بلا حكم. سؤال واحد في كل مرة.",
  zh: "没有错误的答案。没有评判。一次一个问题。",
  "zh-TW": "沒有錯誤的答案。沒有評判。一次一個問題。",
  ja: "間違った答えはありません。判断はありません。一度に一つの質問。",
  ko: "틀린 답은 없어요. 판단도 없어요. 한 번에 질문 하나씩.",
  sv: "Inga fel svar. Ingen dömer. En fråga i taget.",
  no: "Ingen gale svar. Ingen dømming. Ett spørsmål om gangen.",
  da: "Ingen forkerte svar. Ingen dømmekraft. Ét spørgsmål ad gangen.",
  fi: "Ei vääriä vastauksia. Ei tuomitsemista. Yksi kysymys kerrallaan.",
  cs: "Žádné špatné odpovědi. Žádné soudy. Jedna otázka najednou.",
  sk: "Žiadne zlé odpovede. Žiadne súdenie. Jedna otázka naraz.",
  hu: "Nincs rossz válasz. Nincs ítélet. Egyszerre egy kérdés.",
  ro: "Nu există răspunsuri greșite. Fără judecată. O întrebare pe rând.",
  bg: "Няма грешни отговори. Без осъждане. По един въпрос наведнъж.",
  sr: "Nema pogrešnih odgovora. Bez osude. Jedno pitanje odjednom.",
  bs: "Nema pogrešnih odgovora. Bez osuđivanja. Jedno pitanje odjednom.",
  sl: "Ni narobe odgovorov. Brez obsojanja. Eno vprašanje naenkrat.",
  uk: "Немає неправильних відповідей. Без осуду. Одне запитання за раз.",
  el: "Δεν υπάρχουν λάθος απαντήσεις. Χωρίς κρίση. Μία ερώτηση κάθε φορά.",
  he: "אין תשובות שגויות. בלי שיפוט. שאלה אחת בכל פעם.",
  hi: "कोई गलत जवाब नहीं। कोई निर्णय नहीं। एक समय में एक सवाल।",
  bn: "কোনো ভুল উত্তর নেই। কোনো বিচার নেই। একবারে একটি প্রশ্ন।",
  ur: "غلط جواب نہیں۔ کوئی فیصلہ نہیں۔ ایک وقت میں ایک سوال۔",
  fa: "جواب اشتباهی نیست. قضاوتی نیست. هر بار یک پرسش.",
  th: "ไม่มีคำตอบที่ผิด ไม่มีการตัดสิน ทีละหนึ่งคำถาม",
  vi: "Không có câu trả lời sai. Không phán xét. Mỗi lần một câu hỏi.",
  id: "Tidak ada jawaban salah. Tanpa penghakiman. Satu pertanyaan setiap kali.",
  ms: "Tiada jawapan salah. Tiada penghakiman. Satu soalan pada satu masa.",
  tl: "Walang maling sagot. Walang hatol. Isang tanong sa bawat pagkakataon.",
  sw: "Hakuna majibu yasiyo sahihi. Hakuna hukumu. Swali moja kwa wakati.",
  af: "Geen verkeerde antwoorde nie. Geen oordeel nie. Een vraag op 'n slag.",
  et: "Vale vastuseid pole. Kohtu pole. Üks küsimus korraga.",
  lt: "Nėra neteisingų atsakymų. Be vertinimo. Vienas klausimas vienu metu.",
  lv: "Nav nepareizu atbilžu. Bez sprieduma. Viens jautājums vienā reizē.",
  mk: "Нема погрешни одговори. Без осуда. Едно прашање по едно.",
  sq: "Nuk ka përgjigje të gabuara. Pa gjykim. Një pyetje në herë.",
  mn: "Буруу хариулт гэж байхгүй. Шүүлтгүй. Нэг удаад нэг асуулт.",
  ne: "गलत जवाफ छैन। कुनै निर्णय छैन। एक पटकमा एक प्रश्न।",
  pa: "ਗਲਤ ਜਵਾਬ ਨਹੀਂ। ਕੋਈ ਫੈਸਲਾ ਨਹੀਂ। ਇੱਕ ਵਾਰ ਵਿੱਚ ਇੱਕ ਸਵਾਲ।",
  gu: "ખોટા જવાબો નથી. કોઈ નિર્ણય નથી. એક સમયે એક પ્રશ્ન.",
  ta: "தவறான பதில்கள் இல்லை. தீர்ப்பு இல்லை. ஒரு நேரத்தில் ஒரு கேள்வி.",
  te: "తప్పు సమాధానాలు లేవు. నిర్ణయం లేదు. ఒక సారి ఒక ప్రశ్న.",
  kn: "ತಪ್ಪಾದ ಉತ್ತರಗಳಿಲ್ಲ. ನಿರ್ಣಯವಿಲ್ಲ. ಒಂದು ಬಾರಿ ಒಂದು ಪ್ರಶ್ನೆ.",
  ha: "Babu amsar da ba daidai ba. Babu hukunci. Tambaya daya a lokaci.",
  yo: "Ko si idahun ti ko tọ. Ko si idajọ. Béèrè kan nígbà kan.",
  am: "ስህተት ያለው መልስ የለም። ፍርድ የለም። በአንድ ጊዜ አንድ ጥያቄ።",
};
